version: '3'

services:
  client:
    build: ./client
    container_name: client
    restart: on-failure:10
    environment:
      REACT_APP_API_URL: http://localhost:5000
    ports:
      - 3000:3000
  
  mongo:
    image: mongo
    container_name: mongo
    restart: on-failure:10
    ports:
      - 27017:27017

  api:
    build: ./api
    container_name: api
    restart: on-failure:10
    environment:
      MONGO_URI: mongodb://mongo:27017/getapet
      APP_URL: http://localhost:3000
    ports:
      - 5000:5000
    links:
      - mongo